kind: Service
apiVersion: v1
metadata:
  name: polaris
  namespace: gis-team
spec:
  type: ExternalName
  # https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
  externalName: polaris.polaris.svc.cluster.local
  ports:
    - name: port-1
      port: 8181